/*
 * cl_dprep_primecontroller.h
 *
 * Created: 11/3/2014 1:03:31 PM
 *  Author: user
 */ 


#ifndef CL_DPREP_PRIMECONTROLLER_H_
#define CL_DPREP_PRIMECONTROLLER_H_


typedef enum {
	CL_DPREP_PRIME_STATE_IDLE,
	CL_DPREP_PRIME_STATE_PRIMING,
	CL_DPREP_PRIME_STATE_PRIME_COMPLETED,
	CL_DPREP_PRIME_STATE_PRIME_STOPPED,
	CL_DPREP_PRIME_STATE_PRIME_PAUSED,
	CL_DPREP_PRIME_STATE_PRIME_RCIRC_STARTED,
	CL_DPREP_PRIME_STATE_PRIME_RCIRC_STOPPED,
	CL_DPREP_PRIME_STATE_PRIME_RCIRC_PAUSED,
	CL_DPREP_PRIME_STATE_PRIME_RCIRC_COMPLETED,
	CL_DPREP_PRIME_STATE_DIALYSER_PRIMING,
	CL_DPREP_PRIME_STATE_DIALYSER_PRIMING_COMPLETED,
	CL_DPREP_PRIME_STATE_DIALYSER_PRIMING_STOPPED,
	CL_DPREP_PRIME_STATE_DIALYSER_PRIMING_PAUSED,
	CL_DPREP_PRIME_STATE_MAX_STATE
	}Cl_Dprep_PrimeStates;
typedef enum {
	CL_DPREP_PRIME_PRIME_NULL,
	CL_DPREP_PRIME_PRIME_START,
	CL_DPREP_PRIME_PRIME_STOP,
	CL_DPREP_PRIME_PRIME_PAUSE,
	CL_DPREP_PRIME_RCIRC_START,
	CL_DPREP_PRIME_RCIRC_STOP,
	CL_DPREP_PRIME_PRIME_SET_RATE,
	CL_DPREP_PRIME_PRIME_START_DIALYSER_PRIMING,
	CL_DPREP_PRIME_PRIME_STOP_DIALYSER_PRIMING,
	CL_DPREP_PRIME_PRIME_PAUSE_DIALYSER_PRIMING,
	CL_DPREP_PRIME_PRIME_TICK_SEC,
	CL_DPREP_PRIME_BLOODPUMP_START,
	CL_DPREP_PRIME_BLOODPUMP_STOP,
	CL_DPREP_PRIME_BLOODPUMP_SETRATE,
	CL_DPREP_PRIME_PRIME_MAX_EVENT

}Cl_Dprep_PrimeEvents;

#endif /* CL_DPREP_PRIMECONTROLLER_H_ */